openshift:
  adapter: mysql2
  encoding: utf8mb4
  reconnect: false
  database: <%= ENV['MYSQL_DATABASE'] %>
  host: mariadb
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
