apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: lobsters-cron-mail
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            parent: lobsters-cron-mail
        spec:
          restartPolicy: OnFailure
          containers:
            - name: lobsters-cron-mail
              image: docker.io/tobru/lobsters:latest
              imagePullPolicy: Always
              env:
                - name: MYSQL_USER
                  valueFrom:
                    secretKeyRef:
                      key: database-user
                      name: mariadb
                - name: MYSQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: database-password
                      name: mariadb
                - name: MYSQL_DATABASE
                  value: lobsters
              command:
                - "bundle"
                - "exec"
                - "ruby"
                - "script/mail_new_activity"
