apiVersion: batch/v1
kind: Job
metadata:
  name: lobsters-db-initialize
spec:
  template:
    metadata:
      name: lobsters-db-initialize
    spec:
      restartPolicy: Never
      containers:
        - name: lobsters
          image: docker.io/tobru/lobsters:latest
          imagePullPolicy: Always
          env:
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database-root-password
                  name: mariadb
            - name: MYSQL_DATABASE
              value: lobsters
          command:
            - sh
            - -c
            - "rake db:schema:load && rake db:seed"
